### ISSUE TITLE
Error in Build 

### ISSUE THREAD

**Issue by mikrokode** [zeroengineteam/ZeroCore#1412]
Friend,

I am quite new in using zilch library. I got this error when I built it as below. May I know the solution the correct it? 

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'PopulateChildren': is not a member of 'Zilch::NoType'	Zilch	c:\users\admin\desktop\gameengine\zerocore-1.4.2\zerocore-1.4.2\zerolibraries\zilch\project\zilch\syntaxtree.cpp	200

**Comment by mikrokode** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'Equal': is not a member of 'Zero::ComparePolicy<T,void>'	Networking	c:\users\admin\desktop\gameengine\zerocore-1.4.2\zerocore-1.4.2\zerolibraries\common\containers\containercommon.hpp	576	


Another error. I not very familiar with C++. Need your help.

**Comment by mikrokode** [comment]
Friends,

I have succeeded in building all project but with the except of project in the folder of project. (ZeroEditor, BrowserSubProcess, ZeroLauncher, ZeroLauncherSharedLibrary) got error in built.
The error as below, may I know how to solve?

![error](https://user-images.githubusercontent.com/26881536/60356687-34545700-9a04-11e9-9c7d-899e05182c8b.png)

**Comment by jodavis42** [comment]
I haven't seen that error before. When you downloaded the project, how did you go about building it? I'll have to double check later, but I believe the expected work flow is to go into the cmake folder and run the GenerateVS2017.cmd or whatever file in there to run cmake then go into a sub-folder (named via the generated solution config) and run the .sln in there.
